### ISSUE TITLE
Provide more useful error messages

### ISSUE THREAD

**Issue by ysimonson** [shin-/sqlite-wrapper#2]
Whenever a sqlite constraint violation occurs, the error message only gives me this:

  Error: SQLITE_CONSTRAINT: constraint failed

This isn't very helpful. Any way to get more context?

**Comment by shin-** [comment]
Does enabling the debug mode help at all? (i.e. `require('sqlite-wrapper')(dbUrl, true);`). Other than that this is just a wrapper, the error is passed as is from what [node-sqlite3](https://github.com/developmentseed/node-sqlite3) gives us
