### ISSUE TITLE
Arguments being inserted in reverse

### ISSUE THREAD

**Issue by ysimonson** [shin-/sqlite-wrapper#3]
Debugging an issue in addGroupMembers of the stack.io auth API. With debug mode on, it's spitting out this sql:

SELECT id FROM groups WHERE name=?; 
 [ 'test2-group' ]
SELECT id FROM users WHERE username IN (?); 
 [ 'test2' ]
INSERT INTO user_groups (group_id,user_id) SELECT ? AS group_id, ? AS user_id; 
 [ 2, 3 ]

This arguments being inserted seem to be in reverse. There is no user_id=3:

sqlite> SELECT \* FROM users;
1|test|c638833f69bbfb3c267afa0a74434812436b8f08a81fd263c6be6871de4f1265
2|test2|a1159e9df3670d549d04524532629f5477ceb7deec9b45e47e8c009506ecb2c8

sqlite> SELECT \* FROM groups;
1|**anon**
2|test
3|test2-group

Here's the output for user_groups after the insert. Seems like it went through with the reverse arguments:

sqlite> SELECT group_id, user_id from user_groups;
2|1
2|3

If I'm not debugging it incorrectly, this is a strong indicator that more thorough unit tests are needed.

**Comment by shin-** [comment]
Adding code snippet for reference while I look into it.

```
    addGroupMembers: function(name, users, cb) {
        var callback = _.after(proxy(cb), users.length);
        this._getGroupId(name, function(err, result) {
            if (err) {
                return cb(err, null, false);
            } else if (!result) {
                return cb(null, false, false);
            }
            var gid = result.id,
                errors = [];
            db.select('users', null, ['id'], 'username IN (' + 
                repeat('?', ',', users.length) + ')', users, function(err, ids) {
                    if (err) {
                        return cb(err, null, false);
                    }
                    var links = ids.reduce(function(prev, item) {
                        prev.push({
                            group_id: item.id,
                            user_id: gid
                        });
                        return prev;
                    }, []);
                    db.insertAll('user_groups', links, function(err) {
                        cb(err, !err, false);
                    });
            });
        });
    }
```

**Comment by shin-** [comment]
The bug is in addGroupMembers. I'm patching it right now.

**Comment by shin-** [comment]
https://github.com/dotcloud/stack.io/commit/46883a096c849e1e6b7c7865ccea627a1207a3dd

**Comment by ysimonson** [comment]
Cool, thank you
