### ISSUE TITLE
Callback format

### ISSUE THREAD

**Issue by stanonyime** [shin-/sqlite-wrapper#4]
What is the callback format? Is it like:
callback = function(err,data){}
 and if so is err an error object with an err.message property or is it the message itself...More helpful examples will be appreciated

**Comment by shin-** [comment]
Hi! 

Yes, the format is `(err, result)` as per convention in node.js ; err is an error message (sqlite-wrapper only passes through whatever [node-sqlite3](https://github.com/developmentseed/node-sqlite3) reports)

I agree we could have better examples -- I'll try to make some time for it.
